name: Mount node_modules
description: Mount the output of an `npm install` we ran in an earlier job

inputs:
  NODE_MODULES_CACHE_KEY:
    description: "Required, the cache key node_modules can be read from"
    required: true
  NODE_MODULES_PATH:
    description: "Defaults to node_modules"
    default: "node_modules"
    required: false

runs:
  using: "composite"
  steps:
    # Ensure Node.js is available
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: "package.json"

    # Mount the output of an npm install we ran in an earlier job
    - name: Mount node_modules
      id: cache-npm-restore
      uses: actions/cache/restore@v3
      with:
        fail-on-cache-miss: true
        path: ${{ inputs.NODE_MODULES_PATH }}
        key: ${{ inputs.NODE_MODULES_CACHE_KEY }}
