name: Prime Default Caches

on:
  push:
    branches: [main]

env:
  E2E_RESULTS_PATH: test/results
  NEXTJS_BUILD_PATH: .next
  NEXTJS_CACHE_PATH: .next/cache
  NODE_MODULES_PATH: node_modules

jobs:
  prime-default-caches:
    name: Prime Default Caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Generate Cache Keys
        id: CACHE_KEYS
        uses: ./.github/actions/generate-cache-keys
      - name: Cache node_modules
        uses: ./.github/actions/install-node-modules
        with:
          NODE_MODULES_CACHE_KEY: ${{ steps.CACHE_KEYS.outputs.NODE_MODULES_CACHE_KEY }}
          NODE_MODULES_PATH: ${{ env.NODE_MODULES_PATH }}
      - name: Cache .next
        uses: ./.github/actions/build-nextjs
        with:
          NEXTJS_BUILD_CACHE_KEY: ${{ steps.CACHE_KEYS.outputs.NEXTJS_BUILD_CACHE_KEY }}
          NEXTJS_BUILD_PATH: ${{ env.NEXTJS_BUILD_PATH }}
      - name: Cache Browsers
        uses: ./.github/actions/install-browsers
